const sections = [
  {
    slug: "contract-structure",
    title: "Contract structure",
    description: require("./contract-structure/content.md").default,
    solidity: require("./contract-structure/code.sol").default,
    ligo: require("./contract-structure/code.ligo").default,
  },
  {
    slug: "functions-function-modifiers",
    title: "Functions & Function Modifiers",
    description: require("./functions-function-modifiers/content.md").default,
    solidity: require("./functions-function-modifiers/code.sol").default,
    ligo: require("./functions-function-modifiers/code.ligo").default,
  },
  {
    slug: "variables-and-constants",
    title: "Variables and Constants",
    description: require("./variables-and-constants/content.md").default,
    solidity: require("./variables-and-constants/code.sol").default,
    ligo: require("./variables-and-constants/code.ligo").default,
  },
  {
    slug: "booleans",
    title: "Booleans",
    description: require("./booleans/content.md").default,
    solidity: require("./booleans/code.sol").default,
    ligo: require("./booleans/code.ligo").default,
  },
  {
    slug: "numbers",
    title: "Numbers",
    description: require("./numbers/content.md").default,
    solidity: require("./numbers/code.sol").default,
    ligo: require("./numbers/code.ligo").default,
  },
  {
    slug: "addresses",
    title: "Addresses",
    description: require("./addresses/content.md").default,
    solidity: require("./addresses/code.sol").default,
    ligo: require("./addresses/code.ligo").default,
  },
  {
    slug: "bytes-and-strings",
    title: "Bytes and Strings ",
    description: require("./bytes-and-strings/content.md").default,
    solidity: require("./bytes-and-strings/code.sol").default,
    ligo: require("./bytes-and-strings/code.ligo").default,
  },
  {
    slug: "enumerations-practice-1",
    title: "Enumerations + Practice 1",
    description: require("./enumerations-practice-1/content.md").default,
    solidity: require("./enumerations-practice-1/code.sol").default,
    ligo: require("./enumerations-practice-1/code.ligo").default,
  },
  {
    slug: "elementary-types-summary",
    title: "Elementary Types Summary",
    description: require("./elementary-types-summary/content.md").default,
    solidity: require("./elementary-types-summary/code.sol").default,
    ligo: require("./elementary-types-summary/code.ligo").default,
  },
  {
    slug: "structures",
    title: "Structures",
    description: require("./structures/content.md").default,
    solidity: require("./structures/code.sol").default,
    ligo: require("./structures/code.ligo").default,
  },
  {
    slug: "mappings",
    title: "Mappings",
    description: require("./mappings/content.md").default,
    solidity: require("./mappings/code.sol").default,
    ligo: require("./mappings/code.ligo").default,
  },
  {
    slug: "array-like-types",
    title: "Array-like types",
    description: require("./array-like-types/content.md").default,
    solidity: require("./array-like-types/code.sol").default,
    ligo: require("./array-like-types/code.ligo").default,
  },
  {
    slug: "tuples-practice-2",
    title: "Tuples + Practice 2",
    description: require("./tuples-practice-2/content.md").default,
    solidity: require("./tuples-practice-2/code.sol").default,
    ligo: require("./tuples-practice-2/code.ligo").default,
  },
  {
    slug: "lists-practice-3",
    title: "Lists + Practice 3",
    description: require("./lists-practice-3/content.md").default,
    solidity: require("./lists-practice-3/code.sol").default,
    ligo: require("./lists-practice-3/code.ligo").default,
  },
  {
    slug: "sets-practice-4",
    title: "Sets + Practice 4",
    description: require("./sets-practice-4/content.md").default,
    solidity: require("./sets-practice-4/code.sol").default,
    ligo: require("./sets-practice-4/code.ligo").default,
  },
  {
    slug: "complex-types-summary",
    title: "Complex Types Summary",
    description: require("./complex-types-summary/content.md").default,
    solidity: require("./complex-types-summary/code.sol").default,
    ligo: require("./complex-types-summary/code.ligo").default,
  },
  {
    slug: "type-aliases-practice-5",
    title: "Type Aliases + Practice 5",
    description: require("./type-aliases-practice-5/content.md").default,
    solidity: require("./type-aliases-practice-5/code.sol").default,
    ligo: require("./type-aliases-practice-5/code.ligo").default,
  },
  {
    slug: "conditions",
    title: "Conditions",
    description: require("./conditions/content.md").default,
    solidity: require("./conditions/code.sol").default,
    ligo: require("./conditions/code.ligo").default,
  },
  {
    slug: "typecasting",
    title: "Typecasting",
    description: require("./typecasting/content.md").default,
    solidity: require("./typecasting/code.sol").default,
    ligo: require("./typecasting/code.ligo").default,
  },
  {
    slug: "loops",
    title: "Loops",
    description: require("./loops/content.md").default,
    solidity: require("./loops/code.sol").default,
    ligo: require("./loops/code.ligo").default,
  },
  {
    slug: "special-variables",
    title: "Special variables",
    description: require("./special-variables/content.md").default,
    solidity: require("./special-variables/code.sol").default,
    ligo: require("./special-variables/code.ligo").default,
  },
  {
    slug: "imports",
    title: "Imports",
    description: require("./imports/content.md").default,
    solidity: require("./imports/code.sol").default,
    ligo: require("./imports/code.ligo").default,
  },
  {
    slug: "functions-visibility-and-modifiers",
    title: "Functions visibility and modifiers ",
    description: require("./functions-visibility-and-modifiers/content.md")
      .default,
    solidity: require("./functions-visibility-and-modifiers/code.sol").default,
    ligo: require("./functions-visibility-and-modifiers/code.ligo").default,
  },
];

export default sections;
